/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.shalom.view;

import br.com.shalom.dao.GrupoDao;
import br.com.shalom.dao.MinisterioDao;
import br.com.shalom.dao.PessoaDao;
import br.com.shalom.filter.SomenteNumeros;
import br.com.shalom.filter.TeclasPermitidas;
import br.com.shalom.modelo.Endereco;
import br.com.shalom.modelo.Estado;
import br.com.shalom.modelo.Funcao;
import br.com.shalom.modelo.Grupo;
import br.com.shalom.modelo.Ministerio;
import br.com.shalom.modelo.Pessoa;
import br.com.shalom.modelo.Status;
import br.com.shalom.util.JPAUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.hibernate.Session;

/**
 *
 * @author gibran
 */
public class CadastroDePessoas extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroDePessoas
     */
    public CadastroDePessoas() {
        daoGrupo = new GrupoDao();
        daoMinisterio = new MinisterioDao();
        dao = new PessoaDao();
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
	Dimension d = toolkit.getScreenSize();
	int maxX = d.width;
	int maxY = d.height;
	setLocation(maxX / 12, maxY / 22);
        jTextNome.setDocument(new TeclasPermitidas());
        jTextCity.setDocument(new TeclasPermitidas());
        jTextRua.setDocument(new TeclasPermitidas());
        jTextNum.setDocument(new SomenteNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btIncluir = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btListarPessoas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFone = new javax.swing.JFormattedTextField();
        jTextId = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jTextCity = new javax.swing.JTextField();
        jTextRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jComboStatus = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboFuncao = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboMinisterio = new javax.swing.JComboBox();
        jComboGrupo = new javax.swing.JComboBox();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Pessoas");
        setMaximumSize(new java.awt.Dimension(1096, 606));
        setMinimumSize(new java.awt.Dimension(1096, 606));
        setPreferredSize(new java.awt.Dimension(1096, 606));
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/man-48.png"))); // NOI18N
        jLabel4.setText("Cadastro de Pessoas");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(842, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1100, 60);

        jToolBar1.setRollover(true);

        btIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/add1-16.png"))); // NOI18N
        btIncluir.setText("Incluir");
        btIncluir.setFocusable(false);
        btIncluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btIncluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btIncluir);

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/edit16.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setFocusable(false);
        btAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAtualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btAtualizar);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/edit16.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setFocusable(false);
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btExcluir);

        btListarPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/Índice.png"))); // NOI18N
        btListarPessoas.setText("Listar");
        btListarPessoas.setFocusable(false);
        btListarPessoas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btListarPessoas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btListarPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarPessoasActionPerformed(evt);
            }
        });
        jToolBar1.add(btListarPessoas);
        jToolBar1.add(jSeparator2);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/save_16x16.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setEnabled(false);
        btSalvar.setFocusable(false);
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btSalvar);

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/cancel16.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setEnabled(false);
        btCancelar.setFocusable(false);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 1100, 60);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "GRUPO", "MINISTERIO", "TELEFONE", "NASCIMENTO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);
        class AlinharCentro extends DefaultTableCellRenderer{
            public AlinharCentro(){
                setHorizontalAlignment(CENTER);
            }
        }

        TableCellRenderer center = new AlinharCentro();
        jTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable.getColumnModel().getColumn(0).setWidth(30);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable.getColumnModel().getColumn(0).setMaxWidth(30);
        jTable.getColumnModel().getColumn(0).setCellRenderer(center);

        jTable.getColumnModel().getColumn(1).setWidth(150);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(1).setMaxWidth(150);

        jTable.getColumnModel().getColumn(2).setWidth(150);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(2).setMaxWidth(150);

        jTable.getColumnModel().getColumn(3).setWidth(130);
        jTable.getColumnModel().getColumn(3).setPreferredWidth(130);
        jTable.getColumnModel().getColumn(3).setMaxWidth(130);

        jTable.getColumnModel().getColumn(4).setWidth(100);
        jTable.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable.getColumnModel().getColumn(4).setMaxWidth(100);
        jTable.getColumnModel().getColumn(4).setCellRenderer(center);
        jScrollPane1.setViewportView(jTable);

        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(0).setResizable(false);
            jTable.getColumnModel().getColumn(1).setResizable(false);
            jTable.getColumnModel().getColumn(2).setResizable(false);
            jTable.getColumnModel().getColumn(3).setResizable(false);
            jTable.getColumnModel().getColumn(4).setResizable(false);
            jTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(440, 0, 640, 420);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados pessoais"));

        jLabel1.setText("Nome:");

        jTextNome.setEditable(false);

        jLabel2.setText("Data de nascimento:");

        jLabel3.setText("Telefone:");

        jTextFone.setEditable(false);
        try {
            jTextFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFone.setToolTipText("");

        jTextId.setEditable(false);
        jTextId.setVisible(false);

        jDateChooser.setDate(new Date());
        jDateChooser.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 10, 420, 160);

        jTextCity.setEditable(false);

        jTextRua.setEditable(false);

        jLabel7.setText("Cidade:");

        jLabel5.setText("Rua:");

        jTextNum.setEditable(false);

        jLabel6.setText("Número:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextRua, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Endereço", jPanel6);

        jComboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PERMANENTE", "PERIFERICO", "FLUTUANTE", "EVASAO" }));

        jLabel8.setText("Função:");

        jLabel9.setText("Status:");

        jComboFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OVELHA", "PASTOR", "NUCLEO" }));

        jLabel10.setText("Grupo:");

        jLabel11.setText("Ministério:");

        modelos = daoMinisterio.getAllMinisteriosByName(JPAUtil.getSession());
        jComboMinisterio.setModel(new DefaultComboBoxModel(modelos.toArray()));

        modelos = daoGrupo.getAllGroupsByName(JPAUtil.getSession());
        jComboGrupo.setModel(new DefaultComboBoxModel(modelos.toArray()));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboMinisterio, 0, 206, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboMinisterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Dados da comunidade", jPanel7);

        jPanel3.add(jTabbedPane2);
        jTabbedPane2.setBounds(10, 180, 420, 230);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 140, 1080, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        habilitarCamposEdicao();
        estado = Estado.INSERCAO;
    }//GEN-LAST:event_btIncluirActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        desabilitarCamposEdicao();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btListarPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarPessoasActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable.getModel();
        int count = tableModel.getRowCount();
        if (count != 0) {
            for (int i = 0; i < count; i++) {
                tableModel.removeRow(0);
            }
        }
        List<Pessoa> pessoas = dao.getAllPeople(JPAUtil.getSession());
        pessoas.forEach((Pessoa p) -> {
            tableModel.addRow(new String[]{p.getId().toString(), p.getNome(), p.getGrupo().getNome(), 
                              p.getMinisterio().getNome(), p.getTelefone(), f.format(p.getNascimento())});
        });
    }//GEN-LAST:event_btListarPessoasActionPerformed

    private void jTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && (estado == Estado.ATUALIZACAO || estado == Estado.EXTINCAO)) {
            Pessoa p;
            Session s = JPAUtil.getSession();
            p = (Pessoa) s.load(Pessoa.class, Integer.parseInt(jTable.getValueAt(jTable.getSelectedRow(), 0).toString()));
            jTextId.setText(p.getId().toString());
            jTextNome.setText(p.getNome());
            jDateChooser.setDate(p.getNascimento());
            jTextFone.setText(p.getTelefone());
            jTextRua.setText(p.getEndereco().getRua());
            jTextNum.setText(p.getEndereco().getNumero());
            jTextCity.setText(p.getEndereco().getCidade());
            jComboFuncao.setSelectedItem(p.getFuncao().toString());
            jComboStatus.setSelectedItem(p.getStatus().toString());
            jComboGrupo.setSelectedItem(p.getGrupo().getNome());
            jComboMinisterio.setSelectedItem(p.getMinisterio().getNome());
         }
    }//GEN-LAST:event_jTableKeyPressed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        habilitarCamposEdicao();
        estado = Estado.ATUALIZACAO;
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        estado = Estado.EXTINCAO;
        habilitarCamposExtincao();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void habilitarCamposExtincao() {
        btSalvar.setEnabled(true);
        btCancelar.setEnabled(true);
        btIncluir.setEnabled(false);
        btAtualizar.setEnabled(false);
        btListarPessoas.setEnabled(false);
        btExcluir.setEnabled(false);
    }

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Pessoa p = getPessoa();
        gerenciarEstados(p);
        desabilitarCamposEdicao();
        btListarPessoasActionPerformed(evt);
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void gerenciarEstados(Pessoa p) {
        if (estado == Estado.INSERCAO) {
            dao.adicionarPessoa(JPAUtil.getSession(), p);
        }
        if (estado == Estado.ATUALIZACAO) {
            dao.atualizarPessoa(JPAUtil.getSession(),p);
        }
        if (estado == Estado.EXTINCAO) {
            dao.removerPessoa(JPAUtil.getSession(), p);
        }
        estado = Estado.NEUTRO;
    }

    private Pessoa getPessoa() {
        Pessoa p = new Pessoa();
        if (estado == Estado.EXTINCAO) {
            p.setId(Integer.parseInt(jTextId.getText()));
            return p;
        }
        if (estado == Estado.ATUALIZACAO) {
            p.setId(Integer.parseInt(jTextId.getText()));
        }
        Grupo g = new Grupo();
        Ministerio m = new Ministerio();
        Endereco end = new Endereco();
        p.setNome(jTextNome.getText().trim());
        p.setNascimento(jDateChooser.getDate());
        p.setTelefone(jTextFone.getText());
        end.setCidade(jTextCity.getText().trim());
        end.setNumero(jTextNum.getText().trim());
        end.setRua(jTextRua.getText().trim());
        p.setEndereco(end);
        if (jComboFuncao.getSelectedIndex() == 0) {
            p.setFuncao(Funcao.OVELHA);
        }
        if (jComboFuncao.getSelectedIndex() == 1) {
            p.setFuncao(Funcao.PASTOR);
        }
        if (jComboFuncao.getSelectedIndex() == 2) {
            p.setFuncao(Funcao.NUCLEO);
        }
        if (jComboStatus.getSelectedIndex() == 0) {
            p.setStatus(Status.PERMANENTE);
        }
        if (jComboStatus.getSelectedIndex() == 1) {
            p.setStatus(Status.PERIFERICO);
        }
        if (jComboStatus.getSelectedIndex() == 2) {
            p.setStatus(Status.FLUTUANTE);
        }
        if (jComboStatus.getSelectedIndex() == 3) {
            p.setStatus(Status.EVASAO);
        }
        g.setNome(jComboGrupo.getSelectedItem().toString());
        p.setGrupo(g);
        m.setNome(jComboMinisterio.getSelectedItem().toString());
        p.setMinisterio(m);
        return p;
    }

    private void habilitarCamposEdicao() {
        jTextCity.setEditable(true);
        jTextFone.setEditable(true);
        jTextNome.setEditable(true);
        jTextNum.setEditable(true);
        jTextRua.setEditable(true);
        jDateChooser.setEnabled(true);
        btAtualizar.setEnabled(false);
        btCancelar.setEnabled(true);
        btSalvar.setEnabled(true);
        btExcluir.setEnabled(false);
        btIncluir.setEnabled(false);
        btListarPessoas.setEnabled(false);
    }

    private void desabilitarCamposEdicao() {
        jTextCity.setEditable(false);
        jTextFone.setEditable(false);
        jTextNome.setEditable(false);
        jTextNum.setEditable(false);
        jTextRua.setEditable(false);
        jDateChooser.setEnabled(false);
        btAtualizar.setEnabled(true);
        btCancelar.setEnabled(false);
        btSalvar.setEnabled(false);
        btExcluir.setEnabled(true);
        btIncluir.setEnabled(true);
        btListarPessoas.setEnabled(true);
        limparCampos();
    }

    private void limparCampos() {
        jTextCity.setText("");
        jTextFone.setText("");
        jTextNome.setText("");
        jTextNum.setText("");
        jTextRua.setText("");
        jTextId.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btListarPessoas;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboFuncao;
    private javax.swing.JComboBox jComboGrupo;
    private javax.swing.JComboBox jComboMinisterio;
    private javax.swing.JComboBox jComboStatus;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextCity;
    private javax.swing.JFormattedTextField jTextFone;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNum;
    private javax.swing.JTextField jTextRua;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    private final GrupoDao daoGrupo;
    private final MinisterioDao daoMinisterio;
    private final PessoaDao dao;
    private List<String> modelos;
    private static Estado estado = null;
    private final SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
}
