/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.shalom.view;

import br.com.shalom.dao.PessoaDao;
import br.com.shalom.modelo.Pessoa;
import br.com.shalom.util.JPAUtil;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.hibernate.Session;

/**
 *
 * @author gibran
 */
public class PesquisaPessoas extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesquisaPessoas
     */
    public PesquisaPessoas() {
        daoPessoa = new PessoaDao();
        forma = new SimpleDateFormat("dd/MM/yyyy");
        initComponents();
        Toolkit toolkit = Toolkit.getDefaultToolkit();
	Dimension d = toolkit.getScreenSize();
	int maxX = d.width;
	int maxY = d.height;
	setLocation(maxX / 22, maxY / 22);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextPesquisa = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btApagar = new javax.swing.JButton();
        btAtulizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Pesquisa");
        setMaximumSize(new java.awt.Dimension(1200, 606));
        setMinimumSize(new java.awt.Dimension(1200, 606));
        setPreferredSize(new java.awt.Dimension(1200, 606));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(1096, 606));
        jPanel1.setMinimumSize(new java.awt.Dimension(1096, 606));
        jPanel1.setLayout(null);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jTable.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TELEFONE", "GRUPO", "MINISTÉRIO", "FUNÇÃO", "STATUS", "NASCIMENTO", "RUA", "NÚMERO", "CIDADE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setToolTipText(jTable.getToolTipText());
        jTable.getTableHeader().setReorderingAllowed(false);
        class AlinharCentro extends DefaultTableCellRenderer{
            public AlinharCentro(){
                setHorizontalAlignment(CENTER);
            }
        }

        TableCellRenderer center = new AlinharCentro();
        jTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable.getColumnModel().getColumn(0).setWidth(30);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable.getColumnModel().getColumn(0).setMaxWidth(30);
        jTable.getColumnModel().getColumn(0).setCellRenderer(center);

        jTable.getColumnModel().getColumn(1).setWidth(150);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(1).setMaxWidth(150);

        jTable.getColumnModel().getColumn(2).setWidth(100);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable.getColumnModel().getColumn(2).setMaxWidth(100);
        jTable.getColumnModel().getColumn(2).setCellRenderer(center);

        jTable.getColumnModel().getColumn(3).setWidth(150);
        jTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(3).setMaxWidth(150);

        jTable.getColumnModel().getColumn(4).setWidth(150);
        jTable.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(4).setMaxWidth(150);

        jTable.getColumnModel().getColumn(5).setWidth(70);
        jTable.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable.getColumnModel().getColumn(5).setMaxWidth(70);

        jTable.getColumnModel().getColumn(6).setWidth(100);
        jTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTable.getColumnModel().getColumn(6).setMaxWidth(100);

        jTable.getColumnModel().getColumn(7).setWidth(100);
        jTable.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTable.getColumnModel().getColumn(7).setMaxWidth(100);

        jTable.getColumnModel().getColumn(8).setWidth(150);
        jTable.getColumnModel().getColumn(8).setPreferredWidth(150);
        jTable.getColumnModel().getColumn(8).setMaxWidth(150);

        jTable.getColumnModel().getColumn(9).setWidth(50);
        jTable.getColumnModel().getColumn(9).setPreferredWidth(50);
        jTable.getColumnModel().getColumn(9).setMaxWidth(50);
        jTable.getColumnModel().getColumn(9).setCellRenderer(center);
        jScrollPane1.setViewportView(jTable);
        if (jTable.getColumnModel().getColumnCount() > 0) {
            jTable.getColumnModel().getColumn(1).setMaxWidth(300);
            jTable.getColumnModel().getColumn(2).setMaxWidth(200);
            jTable.getColumnModel().getColumn(3).setMaxWidth(300);
            jTable.getColumnModel().getColumn(4).setMaxWidth(200);
            jTable.getColumnModel().getColumn(8).setMaxWidth(200);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1170, 470);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1170, 470));

        jTextPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPesquisaKeyPressed(evt);
            }
        });

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/shalom/imagens/search16.png"))); // NOI18N
        btBuscar.setToolTipText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btApagar.setText("Apagar");
        btApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarActionPerformed(evt);
            }
        });

        btAtulizar.setText("Atualizar");
        btAtulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtulizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(btAtulizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btApagar)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(btApagar)
                    .addComponent(btAtulizar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1080, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String pesquisa = jTextPesquisa.getText().trim();
        if (pesquisa != null && !pesquisa.equals("")) {
            preencherTabelaPesquisa(daoPessoa.getAllPeople(JPAUtil.getSession(), pesquisa));
        } else {
            preencherTabela();
        }

    }//GEN-LAST:event_btBuscarActionPerformed


    private void jTextPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btBuscarActionPerformed(null);
        }
    }//GEN-LAST:event_jTextPesquisaKeyPressed

    private void btApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarActionPerformed
        int[] linhas = jTable.getSelectedRows();
        Pessoa p = new Pessoa();
        for (int i = 0; i < linhas.length; i++) {
            p.setId(Integer.parseInt(jTable.getValueAt(linhas[i], 0).toString()));
            daoPessoa.removerPessoa(JPAUtil.getSession(), p);
        }
        preencherTabela();
    }//GEN-LAST:event_btApagarActionPerformed

    private void btAtulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtulizarActionPerformed
        Session session = JPAUtil.getSession();
        try{
            PopupAtulizar popup = new PopupAtulizar(null, true, carregarPessoa(session));
            popup.setVisible(true);
             preencherTabela();
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Nenhuma linha foi selecionada!");
        }finally{
            session.close();
        }
       
    }//GEN-LAST:event_btAtulizarActionPerformed

    private Pessoa carregarPessoa(Session session) {
        int[] linha = jTable.getSelectedRows();
        Pessoa pessoa;
        if (linha.length != 0) {
            Integer id = Integer.parseInt(jTable.getValueAt(linha[0], 0).toString());
            pessoa = daoPessoa.carregarPessoa(session, id);
            return pessoa;
        }
        
        return null;
    }

    private void preencherTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int count = model.getRowCount();
        if (count != 0) {
            for (int i = 0; i < count; i++) {
                model.removeRow(0);
            }
        }
        List<Pessoa> pessoas = daoPessoa.getAllPeople(JPAUtil.getSession());
        pessoas.forEach(p -> {
            model.addRow(new String[]{p.getId().toString(), p.getNome(), p.getTelefone(), p.getGrupo().getNome(), p.getMinisterio().getNome(), p.getFuncao().toString(), p.getStatus().toString(), forma.format(p.getNascimento()), p.getEndereco().getRua(), p.getEndereco().getNumero(), p.getEndereco().getCidade()});
        });
    }

    private void preencherTabelaPesquisa(List<Pessoa> pessoas) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        int count = model.getRowCount();
        if (count != 0) {
            for (int i = 0; i < count; i++) {
                model.removeRow(0);
            }
        }
        pessoas.forEach(p -> {
            model.addRow(new String[]{p.getId().toString(), p.getNome(), p.getTelefone(), p.getGrupo().getNome(), p.getMinisterio().getNome(), p.getFuncao().toString(), p.getStatus().toString(), forma.format(p.getNascimento()), p.getEndereco().getRua(), p.getEndereco().getNumero(), p.getEndereco().getCidade()});
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApagar;
    private javax.swing.JButton btAtulizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextPesquisa;
    // End of variables declaration//GEN-END:variables
    private PessoaDao daoPessoa;
    private SimpleDateFormat forma;
}
